DoctorClinic/DoctorClinic/Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DoctorClinic.Models
{
    public class Department
    {
        public int Id { get; set; }

        [Required]
        [StringLength(20, ErrorMessage = "The length should be 3 to 20 Character")]
        public string Name { get; set; }
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        public bool IsDeleted { get; set; }

        public virtual List<Doctor> Doctors { get; set; }
        public virtual List<Appointment> Appointments { get; set; }
    }
}

DoctorClinic/DoctorClinic/Controllers/DepartmentsController.cs
using DoctorClinic.BLL;
using DoctorClinic.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoctorClinic.Controllers
{
    public class DepartmentsController : Controller
    {
        bool status = false;
        DepartmentManager departmentManager;
        public DepartmentsController()
        {
            departmentManager = new DepartmentManager();

        }

        //GET: Create Department
        public ActionResult Create()
        {
            if ((string)Session["Role"] != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }


        //POST: Create Department
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Department department)
        {
            if (ModelState.IsValid)
            {
                bool checkName = departmentManager.CheckDepartmentName(department.Name);
                if (checkName)
                {
                    ModelState.AddModelError("Name", "This Name is Already Exist");
                    return View();
                }
                status = departmentManager.Add(department);
                if (status)
                {

                    @ViewBag.Msg = "Department Added Successfully";
                    ModelState.Clear();

                }
                else
                {
                    @ViewBag.Msg = "Department Added Failed !";
                }
            }
            return View();
        }


        //GET: Update Department
        public ActionResult Update(int? id)
        {
            if ((string)Session["Role"] != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }

            Department department = departmentManager.GetById(id);
            if (department == null)
            {
                return RedirectToAction("Error");
            }
            return View(department);
        }


        //POST: Update Department
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(Department department)
        {
            status = departmentManager.Update(department);
            if (status)
            {
                return RedirectToAction("ShowAll");
            }
            return View(department);
        }

        //Show All Department
        public ActionResult ShowAll()
        {
            if ((string)Session["Role"] != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }
            return View(departmentManager.GetAll());
        }


        //Delete a Department
        public JsonResult Delete(int? id)
        {
            status = departmentManager.Delete(id);
            if (status)
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }

        //Check Department Name Availability
        public JsonResult CheckDepartmentName(string name)
        {
            status = departmentManager.CheckDepartmentName(name);
            if (status)
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }

        }
    }
}

DoctorClinic/DoctorClinic/Views/Departments/Create.cshtml
@model DoctorClinic.Models.Department

@{
    ViewBag.Title = "Create";

}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div style="font-size:30px;" class="text-center">Add Department</div>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <a href="@Url.Action("ShowAll")" class="btn btn-primary"><span class="glyphicon glyphicon-th-list"></span> Department List</a><br />
                    </div>
                </div>
                <div class="row">

                    <div class="col-md-6 col-md-offset-3">
                        @using (Html.BeginForm("Create", "Departments", FormMethod.Post, new { id = "form" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    <div class="col-md-offset-3 col-md-9">
                                        @if (ViewBag.Msg != null)
                                        {
                                            <div class="text-center SuccessMsg">@ViewBag.Msg</div>
                                        }
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Department Name" } })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger ErrorMsg" })
                                        <div class="text-danger" id="ErrorMsgForName"></div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control", placeholder = "Write something about Department..." })
                                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-3 col-md-9">
                                        <input type="submit" value="Create" class="btn btn-success btn-block btn-lg" />
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/ProjectScripts/Department/Create_Department.js"></script>

}

DoctorClinic/DoctorClinic/Views/Departments/ShowAll.cshtml
@model IEnumerable<DoctorClinic.Models.Department>

@{
    ViewBag.Title = "ShowAll";
}


<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div style="font-size:30px;" class="text-center">List of Department</div>
            </div>
            <div class="panel-body">
                <div class="row form-group">
                    <div class="col-md-12">
                        <a href="@Url.Action("Create")" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Create Department</a><br />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-bordered table-condensed table-striped table-responsive search-table ">
                            <thead>
                                <tr>

                                    <th>
                                        Name
                                    </th>
                                    <th>
                                        Description
                                    </th>
                                    <th>Action</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr id="DelRow_@item.Id">

                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Description)
                                        </td>

                                        <td>
                                            @Html.ActionLink(" ", "Update", new { id = item.Id }, new { @class = "btn btn-primary glyphicon glyphicon-edit", title = "Update" })
                                            <a href="#" class="btn btn-danger glyphicon glyphicon-trash" onclick="GetDeleteId(@item.Id)" title="Delete"></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>

                        @Html.Hidden("DeleteId")

                        <div id="myModal" class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                Modal content
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>

                                        <h2 class="modal-title">Confirm to Delete Department</h2>
                                    </div>
                                    <div class="modal-body">
                                        <h4>Are you sure to Delete this Department ???</h4>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                        <input type="button" class="btn btn-danger" value="Confirm Delete" id="btnConfirmDelete" />
                                    </div>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/ProjectScripts/Department/ShowAll_Department.js"></script>

}

DoctorClinic/DoctorClinic/Views/Departments/Update.cshtml
@model DoctorClinic.Models.Department

@{
    ViewBag.Title = "Update";
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div style="font-size:30px;" class="text-center">Update Department</div>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <a href="@Url.Action("ShowAll")" class="btn btn-primary"><span class="glyphicon glyphicon-th-list"></span> Department List</a><br />
                    </div>
                </div>
                <div class="row">

                    <div class="col-md-6 col-md-offset-3">
                        @using (Html.BeginForm("Update", "Departments", FormMethod.Post, new { id = "form" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">


                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    <div class="col-md-offset-3 col-md-9">
                                        @if (ViewBag.Msg != null)
                                        {
                                            <div class="text-center SuccessMsg">@ViewBag.Msg</div>
                                        }
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Department Name" } })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger ErrorMsg" })
                                        <div class="text-danger" id="ErrorMsgForName"></div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control", placeholder = "Write something about Department..." })
                                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-3 col-md-9">
                                        <input type="submit" value="Update" class="btn btn-success btn-block btn-lg" />
                                    </div>
                                </div>
                                @Html.Hidden("CurrentName", Model.Name);
                            </div>
                        }
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/ProjectScripts/Department/Update_Department.js"></script>
}