DoctorClinic/DoctorClinic/Controllers/AuthorizationsController.cs
using DoctorClinic.Models;
using DoctorClinic.Models.DatabaseContext;
using DoctorClinic.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoctorClinic.Controllers
{
    public class AuthorizationsController : Controller
    {
        private DoctorClinicDbContext db = new DoctorClinicDbContext();

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Login login)
        {

            if (db.Doctors.Any(model => model.Email == login.Email && model.Password == login.Password))
            {
                int id = db.Doctors.Single(model => model.Email == login.Email && model.Password == login.Password).Id;
                Session["Id"] = id;
                Session["Role"] = "Doctor";
                return RedirectToAction("Index", "Home");
            }
            else if (db.Patients.Any(model => model.Email == login.Email && model.Password == login.Password))
            {
                Patient patient = db.Patients.Single(model => model.Email == login.Email && model.Password == login.Password);
                Session["Id"] = patient.Id;
                Session["PatientEmail"] = patient.Email;
                Session["Role"] = "Patient";
                return RedirectToAction("Index", "Home");
            }
            else if (login.Email == "admin@gmail.com" && login.Password == "1234")
            {
                
                Session["Id"] = "1";
                Session["AdminEmail"] = "Admin@gmail.com";
                Session["Role"] = "Admin";
                return RedirectToAction("AdminDashboard", "Home");
            }
            else
                ViewBag.ErrorMsg = "Incorrect Username or Password";
            return View();

        }

        public ActionResult LogOut()
        {
            Session["Id"] = null;
            Session["Role"] = null;
            return RedirectToAction("Index", "Home");
        }
    }
}

DoctorClinic/DoctorClinic/Controllers/DoctorsController.cs
using AppointmentClinic.BLL;
using DoctorClinic.BLL;
using DoctorClinic.Models;
using DoctorClinic.Models.Region;
using DoctorClinic.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoctorClinic.Controllers
{
    public class DoctorsController : Controller
    {
        bool status = false;
        CommonManager commonManager = new CommonManager();
        DoctorManager doctorManager;
        public DoctorsController()
        {
            doctorManager = new DoctorManager();
        }

        //GET: Create Doctor
        public ActionResult Create()
        {
            if ((string)Session["Role"] != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            ViewBag.DepartmentId = commonManager.GetAllDepartment();
            ViewBag.DivisionId = commonManager.GetAllDivision();
            return View();
        }


        //POST: Create Doctor
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Doctor doctor,HttpPostedFileBase ImageFile)
        {

            if (ImageFile == null)
            {
                ModelState.AddModelError("Image", "Please Upload an Image");
                
            }

            if (ImageFile != null)
            {
                bool isValidFormat = commonManager.CheckImageFormat(ImageFile);
                if (isValidFormat == false)
                {
                    ModelState.AddModelError("Image", "Only jpg , png , jpeg are allowed");
                }
                else
                {
                    byte[] convertedImage = commonManager.ConvertImage(ImageFile);
                    doctor.Image = convertedImage;
                }


            }

            if (ModelState.IsValid)
            {
                bool isExistEmail = doctorManager.CheckDoctorEmail(doctor.Email);
                if (isExistEmail)
                {
                    ModelState.AddModelError("Name", "This Name is Already Exist");
                    return View();
                }
                status = doctorManager.Add(doctor);
                if (status)
                {

                    @ViewBag.Msg = "Doctor Added Successfully";
                    ModelState.Clear();

                }
                else
                {
                    @ViewBag.Msg = "Doctor Added Failed !";
                }
            }
            ViewBag.DepartmentId = commonManager.GetAllDepartment();
            ViewBag.DivisionId = commonManager.GetAllDivision();
            return View();
        }


        //GET: Update Doctor
        public ActionResult Update(int? id)
        {
            if ((string)Session["Role"] != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }

            Doctor doctor = doctorManager.GetById(id);
            if (doctor == null)
            {
                return RedirectToAction("Error");
            }
            ViewBag.DepartmentId = commonManager.GetAllDepartment();
            ViewBag.DivisionId = commonManager.GetAllDivision();
            return View(doctor);
        }


        //POST: Update Doctor
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(Doctor doctor, HttpPostedFileBase ImageFile, byte[] CurrentImage,bool? IsFromDoctorProfile)
        {
            if (ImageFile == null)
            {

                doctor.Image = CurrentImage;
            }

            if (ImageFile != null)
            {
                bool isValidFormat = commonManager.CheckImageFormat(ImageFile);
                if (isValidFormat == false)
                {
                    doctor.Image = CurrentImage;
                    ModelState.AddModelError("Image", "Only jpg , png , jpeg are allowed");
                }
                else
                {
                    doctor.Image = commonManager.ConvertImage(ImageFile);
                }

            }


            if (ModelState.IsValid)
            {

                status = doctorManager.Update(doctor);
                if (status == true)
                {
                    if (IsFromDoctorProfile==true)
                    {
                        return RedirectToAction("ProfileDetail", new { doctor.Id });
                    }
                    return RedirectToAction("ShowAll");
                }
                if (status == false)
                {

                    ViewBag.Msg = "Party Category Added Failed !";
                }

            }

            return View(doctor);
        }

        //Show All Doctor
        public ActionResult ShowAll()
        {
            if ((string)Session["Role"] != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }
            return View(doctorManager.GetAll());
        }


        //Detail of a Doctor
        public ActionResult Details(int? id)
        {
            if ((string)Session["Role"] != "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }
            Doctor doctor = doctorManager.GetById(id);
            if (doctor == null)
            {
                return RedirectToAction("Error", "Home");
            }


            return View(doctor);
        }

        //Delete a Doctor
        public JsonResult Delete(int? id)
        {
            
            status = doctorManager.Delete(id);
            if (status)
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }

        //Check Doctor Email Availability
        public JsonResult CheckDoctorEmail(string Email, string CurrentEmail)
        {

            if (Email == CurrentEmail)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            status = doctorManager.CheckDoctorEmail(Email);
            if (status)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }

        }

        //Get All District
        public JsonResult GetAllDistrictById(int id)
        {
            
            List<District> listOfDistrict = commonManager.GetAllDistrictById(id);
            return Json(listOfDistrict, JsonRequestBehavior.AllowGet);
        }

        //Get All Sub-District
        public JsonResult GetAllSubDistrict(int id)
        {
            List<SubDistrict> listOfSubDistrict = commonManager.GetAllSubDistrictById(id);
            return Json(listOfSubDistrict, JsonRequestBehavior.AllowGet);
        }


        //Get All Hospital
        public JsonResult GetAllHospitalById(int id)
        {
            List<Hospital> listOfHospital = commonManager.GetAllHospitalById(id);
            var filterListOfHospital = listOfHospital.Select(c => new {Id= c.Id,Name= c.Name });

            return Json(filterListOfHospital, JsonRequestBehavior.AllowGet);
        }

        //Profile Information

        public ActionResult ProfileDetail(int? id)
        {
            if ((string)Session["Role"] != "Doctor")
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }
            Doctor doctor = doctorManager.GetById(id);
            if (doctor == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(doctor);
        }


        //Edit Doctor Profile
        public ActionResult EditProfile(int? id)
        {
            if ((string)Session["Role"] != "Doctor")
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }
            Doctor doctor = doctorManager.GetById(id);
            if (doctor == null)
            {
                return RedirectToAction("Error", "Home");
            }

            ViewBag.DepartmentId = commonManager.GetAllDepartment();
            ViewBag.DivisionId = commonManager.GetAllDivision();
            return View(doctor);
        }


        //Get Doctor Appointment
        public ActionResult Appointments()
        {

            if ((string)Session["Role"] != "Doctor")
            {
                return RedirectToAction("Index", "Home");
            }
            int id =Convert.ToInt32(Session["Id"]);
            List<Appointment> appointments = doctorManager.GetAppointmentByDoctorId(id);

            return View(appointments);
        }


        //Details of Patients Appointment
        public ActionResult AppointmentDetails(int? id)
        {
            if ((string)Session["Role"] != "Doctor")
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }
            AppointmentManager appointmentManager = new AppointmentManager();
            Appointment appointment = appointmentManager.GetById(id);
            if (appointment == null)
            {
                return RedirectToAction("Error", "Home");
            }

            Patient patient = appointmentManager.GetPatientByEmail(appointment.PatientEmail);
            Scheduler schedule = appointmentManager.GetSchedule(appointment.Date, appointment.DoctorId);
            //Patient patient = db.Patients.SingleOrDefault(model => model.Email == appointment.PatientId);

DoctorClinic/DoctorClinic/Views/Shared/_FrontEndLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/StyleForFrontEnd.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-default navBackColor">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="BrandDefault h3 " href="#"><span style="color:#0094ff">DOCTOR</span>-<span style="color:red">CLINIC</span></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navLineHeight" id="bs-example-navbar-collapse-1">

                <ul class="nav navbar-nav navbar-right ">
                    <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                    <li><a href="#">Health Tips</a></li>
                    <li><a href="@Url.Action("GetAppointment", "Patients")">Get an Appointment</a></li>
                    <li><a href="@Url.Action("About", "Home")">About Us</a></li>
                    <li><a href="#">Contact</a></li>
                    @if (Session["Id"] == null)
                    {
                        <li><a href="@Url.Action("Login", "Authorizations")">Login/Register</a></li>
                    }
                    @if (Session["Id"] != null && (string)Session["Role"] == "Patient")
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle " data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Patient's Dashboard <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("ProfileDetail","Patients",new {id=(int)Session["Id"] })">Profile</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("Appointments","Patients")">Appointment List</a></li>
                                <li><a href="@Url.Action("GetAppointment", "Patients")">Get An Appointment</a></li>
                            </ul>
                        </li>
                        <li><a href="@Url.Action("LogOut","Authorizations",new {area="" })">Log Out</a></li>
                    }
                    @if (Session["Id"] != null && (string)Session["Role"] == "Doctor")
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle " data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Doctor's Dashboard <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("ProfileDetail","Doctors",new {id=(int)Session["Id"] })">Profile</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("Appointments","Doctors")">Appointment List</a></li>
                                
                            </ul>
                        </li>
                        <li><a href="@Url.Action("LogOut","Authorizations")">Log Out</a></li>
                    }

                    @if (Session["Id"] != null && (string)Session["Role"] == "Admin")
                    {
                        <li><a href="@Url.Action("LogOut","Authorizations")">Log Out</a></li>
                    }


                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

    <div class="container">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/chosen.jquery.min.js"></script>
    <script src="~/Scripts/ProjectScripts/Project.js"></script>
    @RenderSection("scripts", required: false)

</body>
</html>